@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

GET http://{{host}}/users

###
POST http://{{host}}/user
Content-Type: {{contentType}}

{
  "name": "test",
  "age": "20"
} 

###
PUT http://{{host}}/user/cbd3ea2d-275d-46a6-aa22-03d47436b7e6
Content-Type: {{contentType}}

{
  "name": "test",
  "age": "20"
} 

###
DELETE http://{{host}}/user/1